[package]
name = "pyseph/datascope"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A clean DataStore editor plugin for Roblox Studio using Vide"
license = "GPL-3.0"
authors = ["Pyseph"]

[server-dependencies]
Vide = "centau/vide@0.4.0"
